=== tmoreira2020/jminimizer/resources/configuration.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT arguments (classType?,primitiveType?)*>
<!ELEMENT class (constructor*,method*)>
<!ATTLIST class name NMTOKEN #REQUIRED>
<!ELEMENT classType EMPTY>
<!ATTLIST classType name CDATA #REQUIRED>
<!ELEMENT configuration (programClasspath,runtimeClasspath?,inspect,notInspect?, output?, report?)>
<!ELEMENT inspect (class*)>

<!ELEMENT constructor (arguments)>
<!ELEMENT method (arguments,return)>
<!ATTLIST method name CDATA #REQUIRED>

<!ELEMENT notInspect (pattern*)>
<!ELEMENT pattern (#PCDATA)>

<!ELEMENT primitiveType EMPTY>
<!ATTLIST primitiveType name (boolean|byte|char|int|float|long|double) #REQUIRED>

<!ELEMENT return (classType|primitiveType|void)>
<!ELEMENT void EMPTY>

<!ELEMENT programClasspath (url*, directory*, fileset*)>
<!ELEMENT runtimeClasspath (url*, directory*, fileset*)>

<!ELEMENT url (#PCDATA)>
<!ELEMENT directory EMPTY>
<!ATTLIST directory path CDATA #REQUIRED>
<!ELEMENT fileset (file+)>
<!ATTLIST fileset directory CDATA #REQUIRED>
<!ELEMENT file EMPTY>
<!ATTLIST file name CDATA #REQUIRED>

<!ELEMENT output (directory|file)>

<!ELEMENT report (directory, xsl?)>
<!ELEMENT xsl EMPTY>
<!ATTLIST xsl path CDATA #REQUIRED
	encoding (UTF-8|ISO8859-1|ISO8859-15) #REQUIRED>

=== tmoreira2020/jminimizer/tags/alpha-2/src/test/xml/test7.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE configuration SYSTEM "../../../resources/configuration.dtd">
<configuration>
	<programClasspath>
		<directory path="target/test-classes"/>
	</programClasspath>
	<inspect>
		<class name="net.java.dev.jminimizer.test7.Main">
			<method name="main">
				<arguments>
					<classType name="java.lang.String[]"/>
				</arguments>
				<return>
					<void></void>
				</return>
			</method>
		</class>
	</inspect>
	<notInspect>
		<pattern>java*</pattern>
	</notInspect>
	<output>
		<directory path="target/test-jminimizer/test7/classes"/>
	</output>
	<report>
		<directory path="target/test-jminimizer/test7/report"/>
	</report>
</configuration>

=== tmoreira2020/jminimizer/branches/alpha/src/test/xml/XMLMethodInspectorTest-notRemove.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE configuration SYSTEM "../../../resources/configuration.dtd" >
<configuration>
	<inspect>
		<class knowTime="compiletime" name="dummy.Teacher">
			<method name="getJob">
				<arguments>
				</arguments>
				<return>
					<classType name="java.lang.String"/>
				</return>
			</method>
		</class>
	</inspect>
	<notInspect>
		<pattern>java*</pattern>
	</notInspect>
	<notRemove>
		<pattern>org.w3c.dom.*</pattern>
	</notRemove>
</configuration>

=== tmoreira2020/jminimizer/tags/alpha-2/src/test/xml/XMLMethodInspectorTest-notInspect.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE configuration SYSTEM "../../../resources/configuration.dtd" >
<configuration>
	<programClasspath>
	</programClasspath>
	<inspect>
	</inspect>
	<notInspect>
		<pattern>org*</pattern>
		<pattern>java*</pattern>
	</notInspect>
	<output>
		<directory path="target/test-jminimizer/classes"/>
	</output>
	<report>
		<directory path="target/test-jminimizer/report"/>
	</report>
</configuration>

=== tmoreira2020/jminimizer/src/test/xml/XMLMethodInspectorTest-inspect.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE configuration SYSTEM "../../../resources/configuration.dtd" >
<configuration>
	<programClasspath>
	</programClasspath>
	<inspect>
		<class name="dummy.Person">
			<method name="setName">
				<arguments>
					<classType name="java.lang.String"/>
				</arguments>
				<return>
					<void/>
				</return>
			</method>
			<method name="getName">
				<arguments/>
				<return>
					<classType name="java.lang.String"/>
				</return>
			</method>
		</class>
		<class name="dummy.Teacher">
			<constructor>
				<arguments>
					<classType name="dummy.Teacher"/>
				</arguments>
			</constructor >
		</class>
	</inspect>
	<notInspect>
		<pattern>java*</pattern>
	</notInspect>
	<output>
		<directory path="target/test-jminimizer/classes"/>
	</output>
	<report>
		<directory path="target/test-jminimizer/report"/>
	</report>
</configuration>
