=== tmoreira2020/jminimizer/trunk/resources/configuration.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT configuration (programClasspath,runtimeClasspath?,inspect, excludeResources?, notInspect?, output?, report?)>
<!ATTLIST configuration deepStripment (true|false) #IMPLIED>

<!ELEMENT programClasspath (url*, directory*, fileset*)>

<!ELEMENT runtimeClasspath (url*, directory*, fileset*)>

<!ELEMENT url (#PCDATA)>

<!ELEMENT directory EMPTY>
<!ATTLIST directory path CDATA #REQUIRED>

<!ELEMENT fileset (file+)>
<!ATTLIST fileset directory CDATA #REQUIRED>

<!ELEMENT file EMPTY>
<!ATTLIST file name CDATA #REQUIRED>

<!ELEMENT inspect (class*)>

<!ELEMENT class (constructor*,method*)>
<!ATTLIST class name NMTOKEN #REQUIRED>

<!ELEMENT constructor (arguments)>

<!ELEMENT method (arguments,return)>
<!ATTLIST method name CDATA #REQUIRED>

<!ELEMENT arguments (classType?,primitiveType?)*>

<!ELEMENT classType EMPTY>
<!ATTLIST classType name CDATA #REQUIRED>

<!ELEMENT primitiveType EMPTY>
<!ATTLIST primitiveType name (boolean|byte|char|int|float|long|double) #REQUIRED>

<!ELEMENT return (classType|primitiveType|void)>

<!ELEMENT void EMPTY>

<!ELEMENT excludeResources (pattern+)>

<!ELEMENT notInspect (pattern+)>
<!ELEMENT pattern (#PCDATA)>

<!ELEMENT output (directory|file)>

<!ELEMENT report (directory, xsl?)>
<!ELEMENT xsl EMPTY>
<!ATTLIST xsl path CDATA #REQUIRED
	encoding (UTF-8|ISO8859-1|ISO8859-15) #REQUIRED>

=== tmoreira2020/jminimizer/trunk/src/test/xml/test16.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE configuration SYSTEM "../../../resources/configuration.dtd">
<configuration deepStripment="false">
	<programClasspath>
		<directory path="target/test-classes"/>
	</programClasspath>
	<inspect>
		<class name="net.java.dev.jminimizer.test16.Main">
			<method name="main">
				<arguments>
					<classType name="java.lang.String[]"/>
				</arguments>
				<return>
					<void></void>
				</return>
			</method>
		</class>
	</inspect>
	<notInspect>
		<pattern>java*</pattern>
	</notInspect>
	<output>
		<directory path="target/test-jminimizer/test16/classes"/>
	</output>
	<report>
		<directory path="target/test-jminimizer/test16/report"/>
	</report>
</configuration>

=== tmoreira2020/jminimizer/trunk/jminimizer.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE configuration SYSTEM "./resources/configuration.dtd" >
    <configuration>
    <inspect>
        <class name="net.java.dev.jminimizer.JMinimizer" knowTime="compiletime">
            <method name="main">
                <arguments>
                    <classType name="java.lang.String[]"/>
                </arguments>
                <return>
                	<void></void>
                </return>
            </method>
        </class>
		<class name="org.apache.commons.logging.impl.LogFactoryImpl" knowTime="runtime">
			<constructor>
				<arguments>
				</arguments>
			</constructor>
		</class>
		<class name="org.apache.commons.logging.impl.SimpleLog" knowTime="runtime">
			<constructor>
				<arguments>
					<classType name="java.lang.String"/>
				</arguments>
			</constructor>
		</class>
		<class knowTime="runtime" name="org.apache.bcel.generic.GETSTATIC">
			<constructor>
				<arguments>					
				</arguments>
			</constructor>
		</class>
		<class knowTime="runtime" name="org.apache.bcel.generic.ALOAD">
			<constructor>
				<arguments>					
				</arguments>
			</constructor>
		</class>
		<class knowTime="runtime" name="org.apache.bcel.generic.NEW">
			<constructor>
				<arguments>					
				</arguments>
			</constructor>
		</class>
		<class knowTime="runtime" name="org.apache.bcel.generic.FLOAD">
			<constructor>
				<arguments>					
				</arguments>
			</constructor>
		</class>
		<class knowTime="runtime" name="org.apache.bcel.generic.ASTORE">
			<constructor>
				<arguments>					
				</arguments>
			</constructor>
		</class>
		<class knowTime="runtime" name="org.apache.bcel.generic.INVOKESPECIAL">
			<constructor>
				<arguments>					
				</arguments>
			</constructor>
		</class>
		<class knowTime="runtime" name="org.apache.bcel.generic.DLOAD">
			<constructor>
				<arguments>
				</arguments>
			</constructor>
		</class>
		<class knowTime="runtime" name="org.apache.bcel.generic.INVOKESTATIC">
			<constructor>
				<arguments>
				</arguments>
			</constructor>
		</class>
		<class knowTime="runtime" name="org.apache.bcel.generic.ILOAD">
			<constructor>
				<arguments>
				</arguments>
			</constructor>
		</class>
		<class knowTime="runtime" name="org.apache.bcel.generic.INVOKEINTERFACE">
			<constructor>
				<arguments>
				</arguments>
			</constructor>
		</class>
		<class knowTime="runtime" name="org.apache.bcel.generic.GOTO">
			<constructor>
				<arguments>
				</arguments>
			</constructor>
		</class>
		<class knowTime="runtime" name="org.apache.bcel.generic.LDC">
			<constructor>
				<arguments>
				</arguments>
			</constructor>
		</class>
		<class knowTime="runtime" name="org.apache.bcel.generic.INVOKEVIRTUAL">
			<constructor>
				<arguments>
				</arguments>
			</constructor>
		</class>
		<class knowTime="runtime" name="org.apache.bcel.generic.BIPUSH">
			<constructor>
				<arguments>
				</arguments>
			</constructor>
		</class>
    </inspect>
    <notInspect>
    	<pattern>
    		java*
    	</pattern>
    </notInspect>
</configuration>
